name: Keep N8N Alive

on:
  schedule:
    - cron: "*/15 * * * *"   # ping tiap 15 menit
  workflow_dispatch:

jobs:
  ping-n8n:
    runs-on: ubuntu-latest
    steps:
      - name: Ping N8N Health
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.N8N_URL }}/healthz")
          if [ "$STATUS" -eq 200 ]; then
            echo "✅ N8N is alive (status $STATUS)"
          else
            echo "❌ N8N ping failed (status $STATUS)"
            exit 1
          fi
